"""empty message

Revision ID: 70d7ae632aa2
Revises: 
Create Date: 2021-04-01 20:24:27.677587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d7ae632aa2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('mobile', sa.String(length=14), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('pan_no', sa.String(length=10), nullable=True),
    sa.Column('aadhar_no', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aadhar_no'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('pan_no'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Bank_Details',
    sa.Column('account_no', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=True),
    sa.Column('bank_name', sa.String(length=120), nullable=True),
    sa.Column('bank_branch', sa.String(length=120), nullable=True),
    sa.Column('bank_IFSC', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['User_id'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_no')
    )
    op.create_table('demat',
    sa.Column('account_no', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=True),
    sa.Column('Broker_id', sa.Integer(), nullable=True),
    sa.Column('Broker_name', sa.String(length=200), nullable=True),
    sa.Column('Funds_Avail', sa.Numeric(), nullable=True),
    sa.Column('Funds_Blocked', sa.Numeric(), nullable=True),
    sa.Column('Funds_Invested', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['User_id'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demat')
    op.drop_table('Bank_Details')
    op.drop_table('User')
    # ### end Alembic commands ###
